/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-tertiary": "#ffffff",
        "outline-variant": "#c6c6cd",
        "tertiary-fixed-dim": "#dec29a",
        "on-secondary-fixed-variant": "#005049",
        "tertiary": "#000000",
        "secondary-fixed": "#89f5e7",
        "surface": "#f8f9ff",
        "primary-fixed": "#dae2fd",
        "surface-bright": "#f8f9ff",
        "on-surface": "#0b1c30",
        "surface-variant": "#d3e4fe",
        "on-tertiary-container": "#98805d",
        "secondary": "#006a61",
        "on-secondary-fixed": "#00201d",
        "on-primary-fixed-variant": "#3f465c",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#6bd8cb",
        "surface-container-low": "#eff4ff",
        "primary-fixed-dim": "#bec6e0",
        "on-surface-variant": "#45464d",
        "on-tertiary-fixed-variant": "#574425",
        "tertiary-fixed": "#fcdeb5",
        "secondary-container": "#86f2e4",
        "on-primary": "#ffffff",
        "background": "#f8f9ff",
        "inverse-surface": "#213145",
        "tertiary-container": "#271901",
        "on-secondary-container": "#006f66",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary": "#ffffff",
        "surface-dim": "#cbdbf5",
        "on-error": "#ffffff",
        "outline": "#76777d",
        "surface-container": "#e5eeff",
        "on-primary-container": "#7c839b",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#271901",
        "surface-tint": "#565e74",
        "on-background": "#0b1c30",
        "inverse-primary": "#bec6e0",
        "primary-container": "#131b2e",
        "surface-container-highest": "#d3e4fe",
        "primary": "#000000",
        "surface-container-high": "#dce9ff",
        "on-primary-fixed": "#131b2e"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "unit": "4px",
        "max-width": "1440px",
        "gutter": "16px",
        "margin-desktop": "32px",
        "margin-mobile": "16px"
      },
      "fontFamily": {
        "headline-lg": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "mono-data": ["JetBrains Mono", "monospace"]
      },
      "fontSize": {
        "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1", "fontWeight": "500" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "mono-data": ["13px", { "lineHeight": "1", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
