"""epic1_part2_null_fixes

Revision ID: 9e9cdfac1231
Revises: 02c0bc20d42b
Create Date: 2026-06-09 11:39:15.989644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e9cdfac1231'
down_revision: Union[str, Sequence[str], None] = '02c0bc20d42b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Fix existing NULLs before applying NOT NULL constraint
    op.execute("UPDATE llm_recommendations SET risk_reasoning = '' WHERE risk_reasoning IS NULL")
    op.execute("UPDATE llm_recommendations SET rep_feedback_text = '' WHERE rep_feedback_text IS NULL")
    
    op.alter_column('llm_recommendations', 'risk_reasoning',
               existing_type=sa.TEXT(),
               nullable=False,
               server_default=sa.text("''"))
    op.alter_column('llm_recommendations', 'rep_feedback_text',
               existing_type=sa.TEXT(),
               nullable=False,
               server_default=sa.text("''"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llm_recommendations', 'rep_feedback_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('llm_recommendations', 'risk_reasoning',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
