"""epic1_part3_feedback_at_fix

Revision ID: c8144211619f
Revises: 9e9cdfac1231
Create Date: 2026-06-09 11:41:37.199396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8144211619f'
down_revision: Union[str, Sequence[str], None] = '9e9cdfac1231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Fix existing NULLs before applying NOT NULL constraint
    op.execute("UPDATE llm_recommendations SET rep_feedback_at = NOW() WHERE rep_feedback_at IS NULL")
    
    op.alter_column('llm_recommendations', 'rep_feedback_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llm_recommendations', 'rep_feedback_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
