"""epic1_multi_tenancy

Revision ID: c9fa696977e5
Revises: c8144211619f
Create Date: 2026-06-09 12:31:45.561093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9fa696977e5'
down_revision: Union[str, Sequence[str], None] = 'c8144211619f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('zoho_access_token', sa.String(), nullable=True),
    sa.Column('zoho_refresh_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('zoho_deals', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'zoho_deals', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zoho_deals', type_='foreignkey')
    op.drop_column('zoho_deals', 'company_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')
    op.drop_table('companies')
    # ### end Alembic commands ###
